package com.angelhr28.yapechallenge2024.ui.theme

import androidx.compose.ui.graphics.Color

// Colores para el tema claro
val lightPrimary = Color(0xFFB0A6DB)
val lightOnPrimary = Color(0xFF333333)
val lightPrimaryContainer = Color(0xFFE7E4F5)
val lightOnPrimaryContainer = Color(0xFF666666)
val lightSecondary = Color(0xFFC5B8D1)
val lightOnSecondary = Color(0xFF333333)
val lightSecondaryContainer = Color(0xFFEFE9F3)
val lightOnSecondaryContainer = Color(0xFF333333)
val lightTertiary = Color(0xFFAE9ABE)
val lightOnTertiary = Color(0xFF333333)
val lightTertiaryContainer = Color(0xFFEEE6F1)
val lightOnTertiaryContainer = Color(0xFF333333)
val lightError = Color(0xFFCC6666)
val lightErrorContainer = Color(0xFFFFE3E3)
val lightOnError = Color(0xFFFFFFFF)
val lightOnErrorContainer = Color(0xFFCC6666)
val lightBackground = Color(0xFFF4F4F4)
val lightOnBackground = Color(0xFF333333)
val lightSurface = Color(0xFFFFFFFF)
val lightOnSurface = Color(0xFF333333)
val lightSurfaceVariant = Color(0xFFEEEEEE)
val lightOnSurfaceVariant = Color(0xFF333333)
val lightOutline = Color(0xFF999999)
val lightInverseOnSurface = Color(0xFF333333)
val lightInverseSurface = Color(0xFFFFFFFF)
val lightInversePrimary = Color(0xFFB0A6DB)
val lightSurfaceTint = Color(0xFFB0A6DB)
val lightOutlineVariant = Color(0xFFCCCCCC)
val lightScrim = Color(0x99000000)

// Colores para el tema oscuro
val darkPrimary = Color(0xFFB0A6DB)
val darkOnPrimary = Color(0xFFFFFFFF)
val darkPrimaryContainer = Color(0xFF40396C)
val darkOnPrimaryContainer = Color(0xFFB0A6DB)
val darkSecondary = Color(0xFF675F86)
val darkOnSecondary = Color(0xFFFFFFFF)
val darkSecondaryContainer = Color(0xFF867CA9)
val darkOnSecondaryContainer = Color(0xFFFFFFFF)
val darkTertiary = Color(0xFF837999)
val darkOnTertiary = Color(0xFFFFFFFF)
val darkTertiaryContainer = Color(0xFFBDB4C8)
val darkOnTertiaryContainer = Color(0xFFFFFFFF)
val darkError = Color(0xFFCC6666)
val darkErrorContainer = Color(0xFF801515)
val darkOnError = Color(0xFFFFFFFF)
val darkOnErrorContainer = Color(0xFFCC6666)
val darkBackground = Color(0xFF333333)
val darkOnBackground = Color(0xFFFFFFFF)
val darkSurface = Color(0xFF333333)
val darkOnSurface = Color(0xFFFFFFFF)
val darkSurfaceVariant = Color(0xFF666666)
val darkOnSurfaceVariant = Color(0xFFFFFFFF)
val darkOutline = Color(0xFF999999)
val darkInverseOnSurface = Color(0xFFFFFFFF)
val darkInverseSurface = Color(0xFF333333)
val darkInversePrimary = Color(0xFFB0A6DB)
val darkSurfaceTint = Color(0xFFB0A6DB)
val darkOutlineVariant = Color(0xFFCCCCCC)
val darkScrim = Color(0x99000000)
